apiVersion: v1
kind: Service
metadata:
 name: cloud-build-lesson-2
 labels:
   name: cloud-build-lesson-2
spec:
 ports:
 - port: 8080
   targetPort: 8080
 type: NodePort
 selector:
   name: cloud-build-lesson-2

